#### 3.2.8 Variable对象

In [2]:
import tensorflow as tf

# 为Variable对象传入一个初始值3
my_var = tf.Variable(3, name="my_variable")

add = tf.add(5, my_var)
mul = tf.multiply(8, my_var)

sess = tf.Session()
print( sess.run(add, {my_var: 3}) )
print( sess.run(mul, {my_var: 3}) )

8
24


In [3]:
import tensorflow as tf

# 为Variable对象传入一个初始值3
my_var = tf.Variable(3, name="my_variable")

add = tf.add(5, my_var)
mul = tf.multiply(8, my_var)

# init = tf.initialize_all_variables()
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print( sess.run(add) )
print( sess.run(mul) )

8
24


In [4]:
import tensorflow as tf

# 2x2的零矩阵
zeros = tf.zeros([2, 2])

# 长度为6的全1向量
ones = tf.ones([6])

# 3x3x3的张量，其元素服从0~10的均匀分布
uniform = tf.random_uniform([3, 3, 3], minval=0, maxval=10)

# 3x3x3的张量，其元素服从0均值、标准差为2的正态分布
normal = tf.random_normal([3, 3, 3], mean=0.0, stddev=2.0)

# 3x3x3的张量，其元素服从任何偏离均值不会超过2倍标准差的值，从而可以防止有一个或两个元素与该张量中的其他元素显著不同的情况出现
truncated = tf.truncated_normal([3, 3, 3], mean=5.0, stddev=1.0)

sess = tf.Session()
out_zeros = sess.run(zeros)
out_ones = sess.run(ones)
out_uniform = sess.run(uniform)
out_normal = sess.run(normal)
out_truncated = sess.run(truncated)

print( out_zeros )
print( out_ones )
print( out_uniform )
print( out_normal )
print( out_truncated )

[[ 0.  0.]
 [ 0.  0.]]
[ 1.  1.  1.  1.  1.  1.]
[[[ 7.36646748  5.92754126  0.02677441]
  [ 2.65021324  7.22599411  4.18535328]
  [ 9.4065094   2.52592087  3.31845999]]

 [[ 5.38765526  9.91532421  6.73284531]
  [ 4.563447    5.6954813   0.33340216]
  [ 1.97954893  7.14117908  5.79750633]]

 [[ 9.88667965  9.10527229  2.39065886]
  [ 4.48652649  1.77519441  8.96650887]
  [ 1.08305335  9.99290848  8.36886883]]]
[[[ 0.042863    1.74999881 -1.11648512]
  [-1.6436305   0.63539112 -1.43535173]
  [-0.43996078  0.0381521   3.0149281 ]]

 [[-0.88205922  1.48196304 -0.61123294]
  [ 2.38092589  3.58360386  1.60584545]
  [ 0.25116175  2.51354647  0.99681592]]

 [[ 2.77642369 -0.08581628  0.2368466 ]
  [ 1.52422547  1.98154223 -1.5723958 ]
  [ 0.69524586 -0.85520279  0.81700754]]]
[[[ 5.17072773  6.19159508  4.61080551]
  [ 5.30246067  5.33007574  3.20373678]
  [ 4.18813944  5.51578951  4.28698587]]

 [[ 3.73997712  3.08857989  5.04794884]
  [ 4.88521767  4.3528409   3.81345129]
  [ 6.28895664  4

In [5]:
import tensorflow as tf

var1 = tf.Variable(0, name="initialize_me")
var2 = tf.Variable(1, name="no_initialization")

#init = tf.initialize_variables([var1], "init_var1")
init = tf.variables_initializer([var1], "init_var1")

sess = tf.Session()
out = sess.run(init)

print(out)

None


In [6]:
import tensorflow as tf

# 创建一个初值为1的Variable对象
my_var = tf.Variable(1)

# 创建一个Op，使其在每次运行时都将该Variable对象乘以2
my_var_times_two = my_var.assign(my_var * 2)

# 初始化Op
init = tf.global_variables_initializer()

sess = tf.Session()

# 初始化Variable对象
sess.run(init)

# 将Variable对象乘以2，并将其返回
out1 = sess.run(my_var_times_two)
print(out1)
# 输出：2

# 将Variable对象乘以2，并将其返回
out2 = sess.run(my_var_times_two)
print(out2)
# 输出：4

# 将Variable对象乘以2，并将其返回
out3 = sess.run(my_var_times_two)
print(out3)
# 输出：8

2
4
8


In [7]:
import tensorflow as tf

my_var = tf.Variable(1)
out1 = my_var.assign_add(5)
out2 = my_var.assign_sub(2)

# 初始化Op
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print( sess.run(out1) )
## 6
print( sess.run(out2) )
## 4

# 如果希望将所有Variable对象的值重置为初始值，则只需要再次调用global_variables_initializer，也就是运行sess.run(init)
sess.run(init)
print( sess.run(out2) )

6
4
-1
