#### 5.2.2 跨度（strides）

图像的高度为6个像素，宽度为6个像素，而深度为1个通道（6x6x1）

In [3]:
import tensorflow as tf

input_batch = tf.constant([
    [ # 第一个输入(6x6x1)
        [[0.0], [1.0], [2.0], [3.0], [4.0], [5.0]],
        [[0.1], [1.1], [2.1], [3.1], [4.1], [5.1]],
        [[0.2], [1.2], [2.2], [3.2], [4.2], [5.2]],
        [[0.3], [1.3], [2.3], [3.3], [4.3], [5.3]],
        [[0.4], [1.4], [2.4], [3.4], [4.4], [5.4]],
        [[0.5], [1.5], [2.5], [3.5], [4.5], [5.5]]
    ]
])


kernel = tf.constant([ # 卷积核3x3x1
    [[[0.0]], [[0.5]], [[0.0]]],
    [[[0.0]], [[1.0]], [[0.0]]],
    [[[0.0]], [[0.5]], [[0.0]]]
])

print input_batch.shape
print kernel.shape

conv2d = tf.nn.conv2d(input_batch, kernel, use_cudnn_on_gpu=False, strides=[1, 3, 3, 1], padding='SAME')

with tf.Session() as sess:
    print sess.run(conv2d)
    sess.close()

(1, 6, 6, 1)
(3, 3, 1, 1)
[[[[ 2.20000005]
   [ 8.19999981]]

  [[ 2.79999995]
   [ 8.80000019]]]]


In [4]:
import tensorflow as tf

input_batch = tf.constant([
    [ # 第一个输入(6x6x1)
        [[0.0], [1.0], [2.0], [3.0], [4.0], [5.0]],
        [[0.1], [1.1], [2.1], [3.1], [4.1], [5.1]],
        [[0.2], [1.2], [2.2], [3.2], [4.2], [5.2]],
        [[0.3], [1.3], [2.3], [3.3], [4.3], [5.3]],
        [[0.4], [1.4], [2.4], [3.4], [4.4], [5.4]],
        [[0.5], [1.5], [2.5], [3.5], [4.5], [5.5]]
    ]
])


kernel = tf.constant([ # 卷积核3x3x1
    [[[0.0]], [[0.5]], [[0.0]]],
    [[[0.0]], [[1.0]], [[0.0]]],
    [[[0.0]], [[0.5]], [[0.0]]]
])

print input_batch.shape
print kernel.shape

conv2d = tf.nn.conv2d(input_batch, kernel, use_cudnn_on_gpu=False, strides=[1, 2, 2, 1], padding='SAME')

with tf.Session() as sess:
    print sess.run(conv2d)
    sess.close()

(1, 6, 6, 1)
(3, 3, 1, 1)
[[[[  2.20000005]
   [  6.19999981]
   [ 10.19999981]]

  [[  2.5999999 ]
   [  6.60000038]
   [ 10.60000038]]

  [[  2.20000005]
   [  5.19999981]
   [  8.19999981]]]]
